In [1]:
import numpy as np     #Import numpy as np

In [ ]:
#Make a python list => [1,2,3,4,5]

#Convert it into numpy array and print it

In [2]:
list = [1,2,3,4,5]

In [5]:
list_2 = np.array(list)

In [6]:
list_2

array([1, 2, 3, 4, 5])

In [7]:
#Make a python matrix (3 x 3) => [[1,2,3],[4,5,6],[7,8,9]]

#Convert it into numpy array and print it

In [8]:
mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

# [ [1,3,5],

# [7,9,11],

# [13,15,17] ]

In [21]:
mat_2 = [[1,3,5],[7,9,11],[13,15,17]]

In [23]:
np.reshape(mat_2)

TypeError: _reshape_dispatcher() missing 1 required positional argument: 'newshape'

In [24]:
#Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [25]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# Create numpy array => [1,2,3,4,5] and convert it to 2D array with 5 rows

In [27]:
arr = np.array([1,2,3,4,5])

In [32]:
arr.reshape(5,1)

In [30]:
# Print the shape of the above created array

In [33]:
arr.reshape(5,1).shape

(5, 1)

In [34]:
# Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [35]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [36]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr1[2]

3

In [38]:
arr1[3]

4

In [41]:
arr1[8]

9

In [42]:
# Print alternate elements of that array

In [46]:
arr1[0:10:2]

array([1, 3, 5, 7, 9])

In [47]:
# Change last 3 elements into 100 using broadcasting and print

In [48]:
arr1[7:10]=[100]

In [49]:
arr1

array([  1,   2,   3,   4,   5,   6,   7, 100, 100, 100])

In [50]:
# Create a 5 x 5 matrix (fill it with any element you like), print it.

# Then print the middle (3 x 3) matrix.

In [52]:
mat = np.random.rand(5,5)

In [53]:
mat

array([[0.48586826, 0.0923017 , 0.80071055, 0.91822907, 0.91267533],
       [0.74308089, 0.97124464, 0.07303885, 0.89093873, 0.90531581],
       [0.68837807, 0.24563262, 0.65887775, 0.78152037, 0.21525393],
       [0.07343186, 0.8933398 , 0.74843521, 0.84101601, 0.89809388],
       [0.72287575, 0.65259831, 0.41199194, 0.82721233, 0.35440731]])

In [63]:
mat[1:3 2:4]

SyntaxError: invalid syntax (<ipython-input-63-a35968dac06f>, line 1)